CREATE SEQUENCE CONTACTS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CONTACTS (
    ID INTEGER DEFAULT CONTACTS_SEQ.nextval NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    BIRTHDAY DATE NOT NULL
)